import "./globals.css";
import { Inter } from "next/font/google";
import NextAuthSessionProvider from "./providers/sessionProvider";
import ToolBar from "@/components/ToolBar";
import { SummonerInterface } from "@/Interfaces/Summoner";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hiperia Fantasy",
  description: "Generated by create next app",
};

const getSummonerData = async (sum: string): Promise<SummonerInterface> => {
  const res = await fetch(
    `https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-name/${sum}?api_key=${process.env.LOL_API_KEY}`,
    { cache: "force-cache" }
  );

  if (!res.ok) {
    throw new Error("Failed to fetch Riot API Summoner Profile");
  }

  return res.json();
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  const summonerData = await getSummonerData(session?.user?.name as string);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          {session && <ToolBar summoner={summonerData} />}
          <main>{children}</main>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
