import ToolBar from "@/components/ToolBar";
import "./globals.css";
import { Inter } from "next/font/google";
import { SummonerInterface } from "@/Interfaces/Summoner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hiperia Fantasy",
  description: "Generated by create next app",
};

const getSummonerData = async (sum: string): Promise<SummonerInterface> => {
  const res = await fetch(
    `https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-name/${sum}?api_key=${process.env.LOL_API_KEY}`
  );

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary

    throw new Error("Failed to fetch data");
  }

  return res.json();
};

const summonerName: string = "Hisui02";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const summonerData = await getSummonerData(summonerName);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ToolBar summoner={summonerData} />
        <main>{children}</main>
      </body>
    </html>
  );
}
